# Generated by Django 4.2.5 on 2024-01-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('value', models.CharField(max_length=250, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Saldo')),
                ('debit_credit', models.BooleanField(verbose_name='Debe/Haber')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.item', verbose_name='Partida')),
                ('account', models.ForeignKey(limit_choices_to={'parent__parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='catalogue.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
