# Generated by Django 4.2.5 on 2024-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isItemEnd',
            field=models.BooleanField(default=False, verbose_name='Partida de cierre'),
        ),
    ]
