# Generated by Django 4.2.5 on 2024-01-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=250, verbose_name='Concepto')),
                ('initial_value', models.FloatField(blank=True, default=None, null=True, verbose_name='Valor inicial')),
            ],
            options={
                'verbose_name': 'Formula',
                'verbose_name_plural': 'Formulas',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.BooleanField(verbose_name='Operacion')),
                ('Formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stateOfResult.formula', verbose_name='Formula')),
                ('account', models.ForeignKey(limit_choices_to={'parent__parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='catalogue.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Termino',
                'verbose_name_plural': 'Terminos',
            },
        ),
    ]
