# Generated by Django 5.0.3 on 2024-03-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stateOfResult', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='Formula',
            new_name='formula',
        ),
    ]
