# Generated by Django 4.2.5 on 2023-11-13 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='El código se autogenera al guardar la cuenta', max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(max_length=250, verbose_name='Descripción')),
                ('account_r', models.BooleanField(default=False, help_text='Activar si es cuenta complementaria', verbose_name='Cuenta R')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.account', verbose_name='Cuenta padre')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Balance_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_balance', models.BooleanField(default=False)),
                ('main_account', models.OneToOneField(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, to='catalogue.account', verbose_name='Cuenta principal')),
            ],
            options={
                'verbose_name': 'Naturaleza del Saldo',
                'verbose_name_plural': 'Naturaleza de los Saldos',
            },
        ),
    ]
