# Generated by Django 4.2.5 on 2023-10-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='El código se autogenera al guardar la cuenta', max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
